# Generated by Django 4.1.7 on 2023-02-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='items',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
    ]
