# Generated by Django 4.1.7 on 2023-02-22 14:46

from django.db import migrations
import notes.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_list_items_delete_text_delete_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='note_content',
            field=notes.fields.NoteContentField(blank=True, default=[{'body': '<str>', 'type': 'text'}, {'body': {'checked': False, 'item_value': '<str>'}, 'type': 'list_item'}, {'body': {'list_items': [{'body': {'checked': False, 'item_value': '<str>'}, 'type': 'list_item'}, {'body': {'checked': False, 'item_value': '<str>'}, 'type': 'list_item'}], 'title': '<str>'}, 'type': 'list'}], null=True),
        ),
    ]
